
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ManagedStatsOC_Example' 
  pod "ManagedStatsOC", :path => "../"
@end

target 'ManagedStatsOC_Tests' 
  pod "ManagedStatsOC", :path => "../"
@end
