source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ManagedStatsOC_Example', :exclusive => true do
  pod "ManagedStatsOC", :path => "../"
end

target 'ManagedStatsOC_Tests', :exclusive => true do
  pod "ManagedStatsOC", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'AFNetworking', '~> 3.0'
end
