use_frameworks!

use_frameworks!

target 'ManagedStatsOC_Example', :exclusive => true do
  pod 'ManagedStatsOC', '~> 0.1'
end

target 'ManagedStatsOC_Tests', :exclusive => true do
  pod 'ManagedStatsOC', '~> 0.1'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
